### PR TITLE
Add redundancy in favor of losing a few ROFLScale points.

### PR DESCRIPTION
**Pull request by alloy**
Nuff said.

See #1.

### CODE REVIEW

**Comment by madrobby** [comment]
I think this pull request needs some extended discussion before it can go in, as we have plans do release something similar on our commercial _Semicolon.js Enterprise Platform™_.

**Comment by alloy** [comment]
Oh I see. Probably better to have such a discussion on HackerNews, though.

**Comment by drublic** [comment]
This is way to heavy. The complexity of this solution tippled the complexity of the whole library. I really don't like it.
Also I've not seen any test for the SEP (Semicolon.js Enterprise Platform™). Could you pleases add them? Thank you!

**Comment by djcas9** [comment]
Guys, please stop using semicolons properly. You will hurt the feelings of twitter/bootstrap. https://github.com/twitter/bootstrap/issues/3057 - Also, can you port this to coffeescript.. I can't read javascript.

**Comment by drublic** [comment]
@mephux Could you please open another issue for the coffee-script port? Thank you!

**Comment by djcas9** [comment]
Hey @drublic - I opened a pull request. Thank you! :)

**Comment by alloy** [comment]
5 years later, it’s become very clear to me that you do not respect _all_ the time I’ve put into this.

**Pull request closed without merging**
